[package]
name = "nccl-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
candle-core = { version = "0.9", features = ["cuda"] }
cudarc = { version = "0.16", features = ["nccl"], default-features = false}
zerocopy = "0.8"
serde_json = "1"
